---
title: "Survie pour TB"
output: html_notebook
author: "Philippe BALTZINGER"
date: "2023/08/28"

---

```{r setup, include = FALSE}
library(lubridate)
library(readxl)
library(broom)
library(grid)
library(gridExtra)
library(cowplot)
library(magrittr)
library(viridis)
library(ggpubr)
library(janitor)
library(kableExtra)
library(rstatix)
library(tidyverse)
library(survminer)
library(survival)

knitr::opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=FALSE, results='asis', warning = FALSE, message = FALSE)


#constant
# date_format="%d/%m/%Y"
# cell_line=c("WT", "A4", "A23", "D16", "D45")
# timepoint=c(24, 48, 72)
# h_timepoint=c("H0", "H24", "H48", "H72")

#plot modification
plot_theme=theme_bw()+theme(title = element_text(size=18), axis.text = element_text(size=16), legend.text = element_text(size=16, face="bold"))

theme_philippe = function (title_text_size = 12, axis_text_size = 10, legend_text_size = 10,
                           legend_pos = "bottom"){
  theme_bw() %+replace%
    theme(
      title = element_text(size=title_text_size), 
      axis.text = element_text(size=axis_text_size), 
      legend.text = element_text(size=legend_text_size, face="bold"), 
      legend.position = legend_pos
    )
  
}


```

```{r}


data <- 
#read_xlsx("/Users/baltzingerphilippe/Documents/R studio/rstudio_repo/20230828_stat_inclusion_tb.xlsx", sheet = "Feuil2") %>% 
read_xlsx("/Volumes/EXTENSION_MACMI/Analyses R/rstudio_repo/20230828_stat_inclusion_tb.xlsx", sheet = "Feuil2") %>% 
  clean_names() %>% 
  mutate(across(is.POSIXct, ymd))

data

final_data <- 
read_xlsx("/Volumes/EXTENSION_MACMI/Analyses R/rstudio_repo/20230828_stat_inclusion_tb.xlsx", sheet = "final") %>% 
  clean_names() %>% 
  mutate(across(is.POSIXct, ymd))

final_data

```

```{r}

os_data <- 
  data %>% 
  mutate(old_time = as.double(difftime(old_us, ddn))/365, 
         diagnostic_time = ifelse(is.na(diagnostic_inclusion), NA, as.double(difftime(diagnostic_us, ddn, days))), 
         last_time = as.double(difftime(last_us, ddn))/365) %>% 
  arrange(old_time)

os_data

os_final_data <- 
  final_data %>% 
  mutate(time = as.double(difftime(diagnostic_us, ddn))/365) %>% 
  rename(TART = "inclusion")
  
os_final_data


```

```{r}

fit_final <- survfit(Surv(time, TART)~TART, data = os_final_data)

ggsurvplot(fit_final, data = os_final_data, pval = TRUE, risk.table = TRUE, palette = c("blue", "red"), risk.table.height = 0.3)+
  labs(title = "Âge à la première échographie", x = "Âge (années)", y = "Probabilité de l'évènement")
  


```
```{r}


ggsurvplot(fit_final, data = os_final_data, pval = TRUE, palette = c("blue", "red"))+
  labs(title = "Âge à la première échographie", x = "Âge (années)", y = "Probabilité de l'évènement")
  


```

```{r}

fit_old <- survfit(Surv(old_time, old_inclusion)~old_inclusion, data = os_data)

ggsurvplot(fit_old, data = os_data, pval = TRUE)+
  labs(title = "Âge à la première échographie", x = "Âge (années)", y = "Probabilité de l'évènement")
  


```

```{r}

fit_last <- survfit(Surv(last_time)~last_inclusion, data = os_data)

ggsurvplot(fit_last, data = os_data, pval = TRUE)#+
    labs(title = "Âge à l'échographie")


```

```{r}

fit <- survfit(Surv(diagnostic_time)~diagnostic_inclusion, data = os_data)

ggsurvplot(fit, data = os_data, pval = TRUE)


```

```{r}

difftime(ymd("2022/12/01"), ymd("2020/10/05"))

```

