---
title: "Analyse de la survie en fonction des données métaboliques dans les TNE iléales"
output: html_notebook
author: "Philippe BALTZINGER"
date: "2024/09/29"

---

```{r setup, include = FALSE}
library(lubridate)
library(readxl)
library(broom)
library(grid)
library(gridExtra)
library(cowplot)
library(magrittr)
library(viridis)
library(ggpubr)
library(janitor)
library(kableExtra)
library(rstatix)
library(gtsummary)
library(finalfit)
library(survival)
library(survminer)
library(flextable)
library(tidyverse)


knitr::opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=FALSE, results='asis', warning = FALSE, message = FALSE)


#constant
# date_format="%d/%m/%Y"
# cell_line=c("WT", "A4", "A23", "D16", "D45")
# timepoint=c(24, 48, 72)
# h_timepoint=c("H0", "H24", "H48", "H72")

#plot modification
plot_theme=theme_bw()+theme(title = element_text(size=18), axis.text = element_text(size=16), legend.text = element_text(size=16, face="bold"))

theme_philippe = function (title_text_size = 12, axis_text_size = 10, legend_text_size = 10,
                           legend_pos = "bottom"){
  theme_bw() %+replace%
    theme(
      title = element_text(size=title_text_size), 
      axis.text = element_text(size=axis_text_size), 
      legend.text = element_text(size=legend_text_size, face="bold"), 
      legend.position = legend_pos
    )
  
}


```


```{r}
#J'extrais les variables biologiques et classe les timepoints dans l'ordre chronologique
biological_data_names <- c("creat", "hiaa", "dfg", "hb", "plq", "lymphocyte", "asat", "alat", "ggt", "bili", "cga")
timepoint_levels <- c("diagnostic", "pre", "riv","c1_1m", "c1c2", "c2_1m","c2c3","c3_1m", "c3c4", "post_c4", "m4", "m8", "m12", "m18", "m24", "m30", "m36", "m42", "dnn")
sheet_names <-  c("patient", "tumeur", "traitement", "bio_before", "bio_between", "dnn")


```


```{r include = FALSE}


data <- 
map(sheet_names, function(var = .x){
  
  read_xlsx("/Volumes/EXTENSION_MACMI/Analyses R/these_cedric_collen/20240829_bdd_cc.xlsx", sheet = var, na = c("", "NA", "NC", "nc", "na")) %>% 
    janitor::clean_names() %>% 
    select(-contains("_rq")) %>% 
    arrange(code)
  
}) %>% 
  reduce(inner_join, by = "code")

```

```{r include = FALSE}

data


```
```{r include = FALSE}

survive <- read_tsv("/Volumes/EXTENSION_MACMI/Analyses R/these_cedric_collen/20240910_of_pfs_data.tsv")

survive

```

```{r}

code <- 
read_xlsx("/Volumes/EXTENSION_MACMI/Analyses R/rstudio_repo/20240926_liste_id.xlsx", sheet = "code") %>% 
  janitor::clean_names()

```

```{r include = FALSE}
data_filter <- 
left_join(code, data, by = "code") %>% 
  filter(!is.na(diagnostic))

data_filter

```

```{r include = FALSE}
label_metabo <- 
  read_xlsx("20240928_label_metabo.xlsx")

label_metabo
```



```{r}
metabo_wide <- 
map(c("foie", "os", "peritoine", "ganglion"), function(var = .x){
  
  read_xlsx("/Volumes/EXTENSION_MACMI/Analyses R/rstudio_repo/20240927_donnees_metaboliques_philippe.xlsx", sheet = var, na = c("", "NA", "NC", "nc", "na")) %>% 
    janitor::clean_names() 
  
}) %>% 
  bind_rows()
  

metabo_long <- 
  metabo_wide %>% 
  pivot_longer(!matches("id|site"), names_to = "tep", values_to = "value") %>% 
  separate_wider_regex(tep, c(tep = "tep_[[:digit:]]|mtv|site", "_", parametre = ".*"), too_few = "align_start")

```

```{r include = FALSE}
metabo_wide
```


```{r include = FALSE}
metabo_long
```

```{r include = FALSE}

metabo_survival <- 
left_join(code, survive, by = "code") %>% 
  left_join(metabo_wide, by = "id") %>% 
    filter(!is.na(progression))


metabo_survival %>% select(dead)
```

```{r include = FALSE}

metabo_summarized <- 

metabo_wide %>% 
  group_by(site, id) %>% 
  get_summary_stats(matches("tep")) %>% 
  select(id, site, variable, n, mean, median) %>% 
  pivot_wider(names_from = variable, values_from = c("mean", "median"))

metabo_summarized

```


```{r}
metabo_long_summarized <- 
metabo_long %>% 
  group_by(id, site, tep, parametre) %>% 
  get_summary_stats(value, type = "common")
```

```{r include = FALSE}

metabo_long_sum <- 
  metabo_long %>% 
  group_by(id, site, tep, parametre) %>% 
  summarise(sum_cibles= sum(value), 
            moyenne_cibles = mean(value))

metabo_long_sum
```

```{r include = FALSE}

metabo_index <- 
metabo_long_sum %>% 
  select(-moyenne_cibles) %>% 
  pivot_wider(names_from = c(tep, parametre), values_from = sum_cibles) %>% 
  mutate(index_4_0 = ifelse(site == "foie", (tep_4_mtv2-tep_0_mtv2)/tep_0_mtv2, (tep_4_mtv1-tep_0_mtv1)/tep_0_mtv1), 
         index_4_2 = ifelse(site == "foie", (tep_4_mtv2-tep_2_mtv2)/tep_2_mtv2, (tep_4_mtv1-tep_2_mtv1)/tep_2_mtv1),
         index_2_0 = ifelse(site == "foie", (tep_2_mtv2-tep_0_mtv2)/tep_0_mtv2, (tep_2_mtv1-tep_0_mtv1)/tep_0_mtv1), 
         index_suv_4_0 = (tep_4_suv_peak-tep_0_suv_peak)/tep_0_suv_peak, 
         index_suv_4_2 = (tep_4_suv_peak-tep_2_suv_peak)/tep_2_suv_peak, 
         index_suv_2_0 = (tep_2_suv_peak-tep_0_suv_peak)/tep_0_suv_peak) %>% 
  select(matches("index"), id, site)


metabo_index

```
```{r include = FALSE}

survival_data <- 
metabo_long_sum %>% 
  left_join(code, by = "id") %>% 
  left_join(survive, by = "code") %>% 
  filter(!is.na(progression)) %>% 
  pivot_wider(names_from = c(tep, parametre), values_from = c(sum_cibles, moyenne_cibles))


survival_data

```

# J'analyse la survie

## un modèle de cox 

```{r}

explanatory_sum <- 
label_metabo %>% 
  select(label_survie) %>% 
  filter(str_detect(label_survie, "sum")) %>% 
  as_vector()

explanatory_sum

explanatory_mean <- 
label_metabo %>% 
  select(label_survie) %>% 
  filter(str_detect(label_survie, "moy")) %>% 
  as_vector()

explanatory_mean

explanatory_all <- 
label_metabo %>% 
  select(label_survie) %>% 
  as_vector()

explanatory_all


```


Je fais un modèle de cox sur les moyennes sans tri. 
```{r}

survival_data %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_mean
    #explanatory_multi = explanatory_mean,
    #keep_models = TRUE
  ) %>% flextable::flextable()
  


```
Je fais un modèle de cox sur les sommes sans tri. 

```{r}

survival_data %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_sum
    #explanatory_multi = explanatory_mean,
    #keep_models = TRUE
  ) %>% flextable::flextable()
  


```
Je fais un modèle de cox sur les moyennes de SUV et les sommes de MTV uniquement.

Pour le foie 
```{r}
    survival_data %>% 
  filter(site == "foie") %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_all[c(4:5,7:8,10:11,18, 21, 24)], 
    metrics = TRUE
  )

```

Pour l'os : 
```{r}
survival_data %>% 
  filter(site == "os") %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_all[c(4,7,10,18, 21, 24)], 
    metrics = TRUE
  )
```
Pour les ganglions :
```{r}
survival_data %>% 
  filter(site == "ganglion") %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_all[c(4,7,10,18, 21, 24)], 
    metrics = TRUE
  )
```

Pour le péritoine : 
```{r}
survival_data %>% 
  filter(site == "peritoine") %>% 
  finalfit(
    dependent = dependent_pfs, 
    explanatory = explanatory_all[c(4,7,10,18, 21, 24)], 
    metrics = TRUE
  ) %>% kable()
```


```{r}
mykable = function(x){
    kableExtra::kable(x, row.names = FALSE, align = c("l", "l", "r", "r", "r", "r", "r", "r", "r"), format = "html")
}
```

